# ================================
# SFTP CONFIG
# ================================
sftp.host=10.145.129.60
sftp.port=22
sftp.username=syadav
sftp.private.key=C:/Users/sanjay_ya/.ssh/id_rsa
sftp.private.key.passphrase=tibco123
sftp.remote.run.as=


# ================================
# LOGS
# ================================
sftp.payload.log.dir=/tui/tibco/tra/domain/TIB_DOM_ST5/application/logs/Bookings/Payload
local.log.dir=C:/logs
local.log.retention.days=7
sftp.grep.retry.count=3
sftp.grep.retry.wait.ms=10000
sftp.command.timeout.ms=20000
sftp.keepalive.interval.ms=30000
sftp.search.modified.within.days=15
sftp.correlation.max.depth=3
sftp.correlation.max.tokens=100
sftp.correlation.max.jobids=50
sftp.correlation.max.tokens.per.search=3
sftp.block.max.matches.per.file=10
sftp.local.min.block.lines=10
sftp.log.name.filter.enabled=true

# ================================
# REST TRIGGER
# ================================
rest.endpoint=https://test.api.tui/packageOffers/st5/packageOffers_v1
rest.api.key=jyHJES49AYNYVLCgWUwAtcMBKHWfGUb0
rest.method=POST
rest.accept=application/json
rest.content.type=application/json

# ================================
# SOAP / VRP TRIGGER
# ================================
soap.transport=jms
soap.endpoint=
soap.action=
soap.jms.sender=TIL.ST5.TIB-XX.REQ.VRP.XML.V1
soap.jms.receiver=TIL.ST5.TIB-XX.RES.VRP.XML.V1
soap.jms.async=false

# ================================
# EXECUTION CONFIG
# ================================
execution.retry.count=3
execution.wait.ms=3000

# ================================
# PAYLOAD LOCATION
# ================================
payload.base.dir=regression-payloads/
payload.default.file=datahub/default-booking-update.json
payload.manifest.file=manifest.csv

# ================================
# MULTI-SYSTEM EXECUTION SWITCHES
# ================================
system.jms.enabled=true
system.rest.enabled=true
system.soap.enabled=true
system.rabbitmq.enabled=true
unified.trace.report.enabled=true
platform.report.enabled=false
server.error.whitelabel.enabled=false

# ================================
# JMS SIMULATION CONFIG
# ================================
jms.provider=simulation
jms.default.async=false
jms.simulation.consumer.enabled=true
jms.simulation.retry.count=3
jms.simulation.processing.delay.ms=2000
jms.simulation.retry.delay.ms=2000
jms.simulation.log-analyzer.enabled=true

# ================================
# TIBCO EMS CONFIG - PHASE 2 READY
# ================================
ems.host=10.145.129.62
ems.port=16180
ems.user=adminst5
ems.password=adminst5123
ems.queue.sender=TIL.ST5.TIB-XX.REQ.PUBLISHBOOKINGDETAILS.XML.V2
ems.queue.receiver=TIL.ST5.TIB-XX.SUB.RES.SUBRESERVATIONDATAGIPADAPTERBFE.XML.V1

# ================================
# RABBITMQ / NORDICS CONFIG - PHASE 2 READY
# ================================
rabbitmq.simulation.enabled=true
rabbitmq.exchange=NORDICS.BOOKING.EXCHANGE
rabbitmq.routing.key=nordics.booking.update
rabbitmq.queue.receiver=Nordics.Booking.Queue
